<a href="https://colab.research.google.com/github/AbhishekKaushikCV/HCI/blob/main/Create_gaze_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### To create gaze data from  video data using OpenFace (Linux implementation):
- OpenFace should be installed on your  linux system
- Video to process should be downloaded
- Created the gaze dataframe (Where the face is in the frame) for single participant from all the csv files generated from the OpenFace
- Features available in the dataframe: gaze direction vectors, gaze angle vectors in radians,  eye landmarks for both the eyes

In [ ]:
# Importing the required libraries

import os
import json
import glob
import os.path
from pathlib import Path
import subprocess
import pandas as pd

In [ ]:
# Th root path of the partiipant folder

account_path = '/home/ak/fd249093-60d2-4d4f-99d0-3e98954f7711/fd249093-60d2-4d4f-99d0-3e98954f7711'

In [ ]:
# Created a list of all directories in account path
recording_paths = [] # Contains all the paths of recording
for recording in os.listdir(account_path):
    recording_path = os.path.join (account_path, str(recording))
    recording_paths.append(recording_path)
    #print(recording_path)
recording_paths = sorted(recording_paths)
#print(recording_paths)

In [ ]:
    # count the number of sessions
for recording_path in recording_paths:
        #print(recording_path)
        num_session = 0
        for file in os.listdir(recording_path):
            if str(file)[:7] == "Session":
                num_session += 1
                #print(num_session)
        for session in range(num_session):
            session_path = os.path.join(recording_path, "Session "+str(session).zfill(4))
            #print(session_path)
            video_path = os.path.join(session_path, 'video.mp4')
            #print(video_path)
            
            # For rotation, to rotate the each frame from the video to 90 degree
            input_dir = video_path
            v_out = os.path.join(session_path, 'r_video.mp4')
            print(v_out)
            
            subprocess.run(['ffmpeg', '-i',input_dir,  '-metadata:s:v:0', 'rotate=90', '-y',v_out ])

            # To create gaze data, 
            video_path = v_out
            output_dir = session_path
            path_to_execu = "/home/ak/OpenFace/build//bin/FeatureExtraction"


            subprocess.run([path_to_execu,'-f', video_path, '-out_dir', output_dir, "-gaze"])

In [ ]:
# create a dataframe from all the csv files

# count the number of sessions

gaze_df = pd.DataFrame({}) # An empty dataframe

for recording_path in recording_paths:
        #print(recording_path)
        num_session = 0
        for file in os.listdir(recording_path):
            if str(file)[:7] == "Session":
                num_session += 1
                #print(num_session)
        for session in range(num_session):
            session_path = os.path.join(recording_path, "Session "+str(session).zfill(4))
            #print(session_path)
            csv_path = os.path.join(session_path, 'r_video.csv')
            #print(csv_path)
            temp_df = pd.read_csv(csv_path)
            #print(temp_df)
            gaze_df = gaze_df.append(temp_df,ignore_index=True)

In [ ]:
gaze_df.head()

,frame,face_id,timestamp,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,...,eye_lmk_Z_46,eye_lmk_Z_47,eye_lmk_Z_48,eye_lmk_Z_49,eye_lmk_Z_50,eye_lmk_Z_51,eye_lmk_Z_52,eye_lmk_Z_53,eye_lmk_Z_54,eye_lmk_Z_55
0,1,0,0.000,0.0,0,0.0,0.0,0.0,0.0,0.0,...,945.9,947.4,948.1,948.0,948.2,948.5,948.8,948.9,948.7,948.3
1,2,0,0.034,0.0,0,0.0,0.0,0.0,0.0,0.0,...,945.9,947.4,948.1,948.0,948.2,948.5,948.8,948.9,948.7,948.3
2,3,0,0.069,0.0,0,0.0,0.0,0.0,0.0,0.0,...,945.9,947.4,948.1,948.0,948.2,948.5,948.8,948.9,948.7,948.3
3,4,0,0.103,0.0,0,0.0,0.0,0.0,0.0,0.0,...,945.9,947.4,948.1,948.0,948.2,948.5,948.8,948.9,948.7,948.3
4,5,0,0.138,0.0,0,0.0,0.0,0.0,0.0,0.0,...,945.9,947.4,948.1,948.0,948.2,948.5,948.8,948.9,948.7,948.3

In [ ]:
# Column names
column_names = list(gaze_df.columns)
column_names

['frame',
 'face_id',
 'timestamp',
 'confidence',
 'success',
 'gaze_0_x',
 'gaze_0_y',
 'gaze_0_z',
 'gaze_1_x',
 'gaze_1_y',
 'gaze_1_z',
 'gaze_angle_x',
 'gaze_angle_y',
 'eye_lmk_x_0',
 'eye_lmk_x_1',
 'eye_lmk_x_2',
 'eye_lmk_x_3',
 'eye_lmk_x_4',
 'eye_lmk_x_5',
 'eye_lmk_x_6',
 'eye_lmk_x_7',
 'eye_lmk_x_8',
 'eye_lmk_x_9',
 'eye_lmk_x_10',
 'eye_lmk_x_11',
 'eye_lmk_x_12',
 'eye_lmk_x_13',
 'eye_lmk_x_14',
 'eye_lmk_x_15',
 'eye_lmk_x_16',
 'eye_lmk_x_17',
 'eye_lmk_x_18',
 'eye_lmk_x_19',
 'eye_lmk_x_20',
 'eye_lmk_x_21',
 'eye_lmk_x_22',
 'eye_lmk_x_23',
 'eye_lmk_x_24',
 'eye_lmk_x_25',
 'eye_lmk_x_26',
 'eye_lmk_x_27',
 'eye_lmk_x_28',
 'eye_lmk_x_29',
 'eye_lmk_x_30',
 'eye_lmk_x_31',
 'eye_lmk_x_32',
 'eye_lmk_x_33',
 'eye_lmk_x_34',
 'eye_lmk_x_35',
 'eye_lmk_x_36',
 'eye_lmk_x_37',
 'eye_lmk_x_38',
 'eye_lmk_x_39',
 'eye_lmk_x_40',
 'eye_lmk_x_41',
 'eye_lmk_x_42',
 'eye_lmk_x_43',
 'eye_lmk_x_44',
 'eye_lmk_x_45',
 'eye_lmk_x_46',
 'eye_lmk_x_47',
 'eye_lmk_x_48',
 'eye_lmk_x_49',
 'eye_lmk_x_50',
 'eye_lmk_x_51',
 'eye_lmk_x_52',
 'eye_lmk_x_53',
 'eye_lmk_x_54',
 'eye_lmk_x_55',
 'eye_lmk_y_0',
 'eye_lmk_y_1',
 'eye_lmk_y_2',
 'eye_lmk_y_3',
 'eye_lmk_y_4',
 'eye_lmk_y_5',
 'eye_lmk_y_6',
 'eye_lmk_y_7',
 'eye_lmk_y_8',
 'eye_lmk_y_9',
 'eye_lmk_y_10',
 'eye_lmk_y_11',
 'eye_lmk_y_12',
 'eye_lmk_y_13',
 'eye_lmk_y_14',
 'eye_lmk_y_15',
 'eye_lmk_y_16',
 'eye_lmk_y_17',
 'eye_lmk_y_18',
 'eye_lmk_y_19',
 'eye_lmk_y_20',
 'eye_lmk_y_21',
 'eye_lmk_y_22',
 'eye_lmk_y_23',
 'eye_lmk_y_24',
 'eye_lmk_y_25',
 'eye_lmk_y_26',
 'eye_lmk_y_27',
 'eye_lmk_y_28',
 'eye_lmk_y_29',
 'eye_lmk_y_30',
 'eye_lmk_y_31',
 'eye_lmk_y_32',
 'eye_lmk_y_33',
 'eye_lmk_y_34',
 'eye_lmk_y_35',
 'eye_lmk_y_36',
 'eye_lmk_y_37',
 'eye_lmk_y_38',
 'eye_lmk_y_39',
 'eye_lmk_y_40',
 'eye_lmk_y_41',
 'eye_lmk_y_42',
 'eye_lmk_y_43',
 'eye_lmk_y_44',
 'eye_lmk_y_45',
 'eye_lmk_y_46',
 'eye_lmk_y_47',
 'eye_lmk_y_48',
 'eye_lmk_y_49',
 'eye_lmk_y_50',
 'eye_lmk_y_51',
 'eye_lmk_y_52',
 'eye_lmk_y_53',
 'eye_lmk_y_54',
 'eye_lmk_y_55',
 'eye_lmk_X_0',
 'eye_lmk_X_1',
 'eye_lmk_X_2',
 'eye_lmk_X_3',
 'eye_lmk_X_4',
 'eye_lmk_X_5',
 'eye_lmk_X_6',
 'eye_lmk_X_7',
 'eye_lmk_X_8',
 'eye_lmk_X_9',
 'eye_lmk_X_10',
 'eye_lmk_X_11',
 'eye_lmk_X_12',
 'eye_lmk_X_13',
 'eye_lmk_X_14',
 'eye_lmk_X_15',
 'eye_lmk_X_16',
 'eye_lmk_X_17',
 'eye_lmk_X_18',
 'eye_lmk_X_19',
 'eye_lmk_X_20',
 'eye_lmk_X_21',
 'eye_lmk_X_22',
 'eye_lmk_X_23',
 'eye_lmk_X_24',
 'eye_lmk_X_25',
 'eye_lmk_X_26',
 'eye_lmk_X_27',
 'eye_lmk_X_28',
 'eye_lmk_X_29',
 'eye_lmk_X_30',
 'eye_lmk_X_31',
 'eye_lmk_X_32',
 'eye_lmk_X_33',
 'eye_lmk_X_34',
 'eye_lmk_X_35',
 'eye_lmk_X_36',
 'eye_lmk_X_37',
 'eye_lmk_X_38',
 'eye_lmk_X_39',
 'eye_lmk_X_40',
 'eye_lmk_X_41',
 'eye_lmk_X_42',
 'eye_lmk_X_43',
 'eye_lmk_X_44',
 'eye_lmk_X_45',
 'eye_lmk_X_46',
 'eye_lmk_X_47',
 'eye_lmk_X_48',
 'eye_lmk_X_49',
 'eye_lmk_X_50',
 'eye_lmk_X_51',
 'eye_lmk_X_52',
 'eye_lmk_X_53',
 'eye_lmk_X_54',
 'eye_lmk_X_55',
 'eye_lmk_Y_0',
 'eye_lmk_Y_1',
 'eye_lmk_Y_2',
 'eye_lmk_Y_3',
 'eye_lmk_Y_4',
 'eye_lmk_Y_5',
 'eye_lmk_Y_6',
 'eye_lmk_Y_7',
 'eye_lmk_Y_8',
 'eye_lmk_Y_9',
 'eye_lmk_Y_10',
 'eye_lmk_Y_11',
 'eye_lmk_Y_12',
 'eye_lmk_Y_13',
 'eye_lmk_Y_14',
 'eye_lmk_Y_15',
 'eye_lmk_Y_16',
 'eye_lmk_Y_17',
 'eye_lmk_Y_18',
 'eye_lmk_Y_19',
 'eye_lmk_Y_20',
 'eye_lmk_Y_21',
 'eye_lmk_Y_22',
 'eye_lmk_Y_23',
 'eye_lmk_Y_24',
 'eye_lmk_Y_25',
 'eye_lmk_Y_26',
 'eye_lmk_Y_27',
 'eye_lmk_Y_28',
 'eye_lmk_Y_29',
 'eye_lmk_Y_30',
 'eye_lmk_Y_31',
 'eye_lmk_Y_32',
 'eye_lmk_Y_33',
 'eye_lmk_Y_34',
 'eye_lmk_Y_35',
 'eye_lmk_Y_36',
 'eye_lmk_Y_37',
 'eye_lmk_Y_38',
 'eye_lmk_Y_39',
 'eye_lmk_Y_40',
 'eye_lmk_Y_41',
 'eye_lmk_Y_42',
 'eye_lmk_Y_43',
 'eye_lmk_Y_44',
 'eye_lmk_Y_45',
 'eye_lmk_Y_46',
 'eye_lmk_Y_47',
 'eye_lmk_Y_48',
 'eye_lmk_Y_49',
 'eye_lmk_Y_50',
 'eye_lmk_Y_51',
 'eye_lmk_Y_52',
 'eye_lmk_Y_53',
 'eye_lmk_Y_54',
 'eye_lmk_Y_55',
 'eye_lmk_Z_0',
 'eye_lmk_Z_1',
 'eye_lmk_Z_2',
 'eye_lmk_Z_3',
 'eye_lmk_Z_4',
 'eye_lmk_Z_5',
 'eye_lmk_Z_6',
 'eye_lmk_Z_7',
 'eye_lmk_Z_8',
 'eye_lmk_Z_9',
 'eye_lmk_Z_10',
 'eye_lmk_Z_11',
 'eye_lmk_Z_12',
 'eye_lmk_Z_13',
 'eye_lmk_Z_14',
 'eye_lmk_Z_15',
 'eye_lmk_Z_16',
 'eye_lmk_Z_17',
 'eye_lmk_Z_18',
 'eye_lmk_Z_19',
 'eye_lmk_Z_20',
 'eye_lmk_Z_21',
 'eye_lmk_Z_22',
 'eye_lmk_Z_23',
 'eye_lmk_Z_24',
 'eye_lmk_Z_25',
 'eye_lmk_Z_26',
 'eye_lmk_Z_27',
 'eye_lmk_Z_28',
 'eye_lmk_Z_29',
 'eye_lmk_Z_30',
 'eye_lmk_Z_31',
 'eye_lmk_Z_32',
 'eye_lmk_Z_33',
 'eye_lmk_Z_34',
 'eye_lmk_Z_35',
 'eye_lmk_Z_36',
 'eye_lmk_Z_37',
 'eye_lmk_Z_38',
 'eye_lmk_Z_39',
 'eye_lmk_Z_40',
 'eye_lmk_Z_41',
 'eye_lmk_Z_42',
 'eye_lmk_Z_43',
 'eye_lmk_Z_44',
 'eye_lmk_Z_45',
 'eye_lmk_Z_46',
 'eye_lmk_Z_47',
 'eye_lmk_Z_48',
 'eye_lmk_Z_49',
 'eye_lmk_Z_50',
 'eye_lmk_Z_51',
 'eye_lmk_Z_52',
 'eye_lmk_Z_53',
 'eye_lmk_Z_54',
 'eye_lmk_Z_55']

In [ ]:
# Remove the face_id column
gaze_df = gaze_df.drop(['face_id'], axis=1)

In [ ]:
gaze_df

,frame,timestamp,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,...,eye_lmk_Z_46,eye_lmk_Z_47,eye_lmk_Z_48,eye_lmk_Z_49,eye_lmk_Z_50,eye_lmk_Z_51,eye_lmk_Z_52,eye_lmk_Z_53,eye_lmk_Z_54,eye_lmk_Z_55
0,1,0.000,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,...,945.9,947.4,948.1,948.0,948.2,948.5,948.8,948.9,948.7,948.3
1,2,0.034,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,...,945.9,947.4,948.1,948.0,948.2,948.5,948.8,948.9,948.7,948.3
2,3,0.069,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,...,945.9,947.4,948.1,948.0,948.2,948.5,948.8,948.9,948.7,948.3
3,4,0.103,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,...,945.9,947.4,948.1,948.0,948.2,948.5,948.8,948.9,948.7,948.3
4,5,0.138,0.00,0,0.0,0.0,0.0,0.0,0.0,0.0,...,945.9,947.4,948.1,948.0,948.2,948.5,948.8,948.9,948.7,948.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1089725,5639,191.119,0.03,0,0.0,0.0,0.0,0.0,0.0,0.0,...,97.7,97.3,99.4,99.7,100.4,100.9,101.1,100.7,100.1,99.5
1089726,5640,191.153,0.03,0,0.0,0.0,0.0,0.0,0.0,0.0,...,129.5,128.9,130.4,130.5,131.0,131.4,131.7,131.6,131.1,130.7
1089727,5641,191.186,0.03,0,0.0,0.0,0.0,0.0,0.0,0.0,...,108.5,110.4,111.4,111.1,112.0,113.5,114.8,115.1,114.2,112.7
1089728,5642,191.220,0.03,0,0.0,0.0,0.0,0.0,0.0,0.0,...,154.4,156.1,157.8,156.9,157.0,158.0,159.3,160.3,160.2,159.2
1089729,5643,191.254,0.22,0,0.0,0.0,0.0,0.0,0.0,0.0,...,106.9,106.7,106.8,107.2,107.6,108.0,107.9,107.6,107.1,106.8

In [ ]:
gaze_df.shape

(1089730, 292)

In [ ]:
# Contains rows where success == 1 (Face in the frame)
gaze_df = gaze_df.loc[gaze_df['success']==1]

In [ ]:
gaze_df.reset_index(drop = True,inplace = True)

In [ ]:
gaze_df

,frame,timestamp,confidence,success,gaze_0_x,gaze_0_y,gaze_0_z,gaze_1_x,gaze_1_y,gaze_1_z,...,eye_lmk_Z_46,eye_lmk_Z_47,eye_lmk_Z_48,eye_lmk_Z_49,eye_lmk_Z_50,eye_lmk_Z_51,eye_lmk_Z_52,eye_lmk_Z_53,eye_lmk_Z_54,eye_lmk_Z_55
0,13,0.414,0.98,1,0.023760,-0.056186,-0.998138,-0.277598,-0.055839,-0.959073,...,231.8,233.5,235.5,235.3,234.9,234.6,234.5,234.7,235.1,235.4
1,14,0.448,0.98,1,0.005874,-0.060242,-0.998167,-0.254226,-0.056938,-0.965467,...,227.0,228.8,230.1,229.9,229.4,229.0,229.0,229.2,229.7,230.0
2,15,0.483,0.98,1,0.076759,-0.067117,-0.994788,-0.220747,-0.078165,-0.972194,...,235.6,237.0,238.5,238.6,238.3,237.8,237.4,237.3,237.6,238.1
3,16,0.517,0.98,1,0.039651,-0.054306,-0.997737,-0.220221,-0.062930,-0.973418,...,231.6,232.8,234.8,234.9,234.8,234.5,234.2,234.1,234.2,234.5
4,17,0.552,0.98,1,0.044446,-0.081016,-0.995721,-0.208138,-0.073714,-0.975318,...,234.1,235.6,237.3,237.2,236.9,236.5,236.3,236.3,236.6,237.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
818797,5631,190.847,0.98,1,-0.377356,0.012089,-0.925989,-0.371549,0.027473,-0.928007,...,153.2,153.9,154.8,154.9,155.6,156.4,156.8,156.7,156.1,155.3
818798,5632,190.881,0.98,1,-0.400465,-0.022432,-0.916037,-0.360850,0.017121,-0.932467,...,148.3,148.4,148.5,148.9,149.6,150.2,150.3,149.9,149.2,148.7
818799,5633,190.915,0.98,1,-0.410122,-0.077703,-0.908715,-0.353260,0.028198,-0.935100,...,150.3,150.2,149.3,149.7,150.3,150.6,150.5,150.0,149.5,149.2
818800,5634,190.949,0.98,1,-0.495419,-0.131740,-0.858606,-0.359495,0.008041,-0.933113,...,151.4,151.6,151.3,151.6,152.1,152.4,152.4,152.1,151.6,151.3
818801,5635,190.983,0.98,1,-0.477607,-0.134788,-0.868173,-0.376274,-0.042207,-0.925546,...,133.1,134.1,132.5,132.6,132.3,131.8,131.4,131.3,131.6,132.1

### **A liitle description of the columns:**

- **'frame'** the number of the frame (in case of sequences)

- **'confidence'** how confident is the tracker in current landmark detection estimage

- **'success'** is the track successful (is there a face in the frame or do we think we tracked it well)

### **Gaze Related:** 
- **'gaze_0_x, gaze_0_y, gaze_0_z':** Eye gaze direction vector in world coordinates for eye 0 (normalized), eye 0 is the leftmost eye in the image (think of it as a ray going from the left eye in the image in the direction of the eye gaze)

- **'gaze_1_x, gaze_1_y, gaze_1_z':** Eye gaze direction vector in world coordinates for eye 1 (normalized), eye 1 is the rightmost eye in the image (think of it as a ray going from the right eye in the image in the direction of the eye gaze)

- **'gaze_angle_x, gaze_angle_y':** Eye gaze direction in radians in world coordinates averaged for both eyes and converted into more easy to use format than gaze vectors. If a person is looking left-right this will results in the change of gaze_angle_x (from positive to negative) and, if a person is looking up-down this will result in change of gaze_angle_y (from negative to positive), if a person is looking straight ahead both of the angles will be close to 0 (within measurement error).

- **'eye_lmk_x_0, eye_lmk_x_1,... eye_lmk_x55, eye_lmk_y_1,... eye_lmk_y_55':** location of 2D eye region landmarks in pixels. The landmark index can be found below

- **'eye_lmk_X_0, eye_lmk_X_1,... eye_lmk_X55, eye_lmk_Y_0,... eye_lmk_Z_55':** location of 3D eye region landmarks in millimeters. The landmark index can be found below

In [ ]:
# Export dataframe to csv file 
gaze_df.to_csv(r'/home/ak/fd249093-60d2-4d4f-99d0-3e98954f7711/gaze_df.csv')